# Generated by Django 5.1.5 on 2025-02-03 00:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='needs_restock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='restock_level',
            field=models.IntegerField(default=10, help_text='Minimum quantity before restock is needed', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_bulk_quantity',
            field=models.IntegerField(default=12),
        ),
    ]
