# Generated by Django 5.1.5 on 2025-02-14 02:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_product_needs_restock_product_restock_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bulksale',
            options={},
        ),
        migrations.AlterModelOptions(
            name='regularsale',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='bulksale',
            name='stock_bulks_id_6ef84a_idx',
        ),
        migrations.RemoveIndex(
            model_name='bulksale',
            name='stock_bulks_name_f22e89_idx',
        ),
        migrations.RemoveIndex(
            model_name='bulksale',
            name='stock_bulks_created_fbc9f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='regularsale',
            name='stock_regul_id_7a654c_idx',
        ),
        migrations.RemoveIndex(
            model_name='regularsale',
            name='stock_regul_name_152cf2_idx',
        ),
        migrations.RemoveIndex(
            model_name='regularsale',
            name='stock_regul_created_1eaa5c_idx',
        ),
        migrations.RenameField(
            model_name='bulksale',
            old_name='buyer',
            new_name='seller',
        ),
        migrations.RemoveField(
            model_name='bulksale',
            name='available',
        ),
        migrations.RemoveField(
            model_name='bulksale',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bulksale',
            name='name',
        ),
        migrations.RemoveField(
            model_name='bulksale',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='regularsale',
            name='available',
        ),
        migrations.RemoveField(
            model_name='regularsale',
            name='description',
        ),
        migrations.RemoveField(
            model_name='regularsale',
            name='name',
        ),
        migrations.RemoveField(
            model_name='regularsale',
            name='slug',
        ),
        migrations.AlterField(
            model_name='bulksale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_sales', to='stock.product'),
        ),
        migrations.AlterField(
            model_name='bulksale',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='bulksale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inventorystatement',
            name='total_income',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='inventorystatement',
            name='total_products_in_stock',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='inventorystatement',
            name='total_products_sold',
            field=models.IntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='bulk_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='minimum_bulk_quantity',
            field=models.IntegerField(default=12, help_text='Minimum quantity required for bulk pricing.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='restock_level',
            field=models.IntegerField(default=0, help_text='Minimum quantity before restock is needed.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='regularsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_sales', to='stock.product'),
        ),
        migrations.AlterField(
            model_name='regularsale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
