# Generated by Django 5.1.5 on 2025-03-05 19:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_regularsale_product_remove_regularsale_seller_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('bulk', 'Bulk')], default='regular', max_length=10),
        ),
    ]
