# Generated by Django 5.1.5 on 2025-03-08 13:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_sale_user_alter_saleitem_sale_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorystatement',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='inventorystatement',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='inventorystatement',
            name='total_products_in_stock',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='inventorystatement',
            name='total_products_sold',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
