# Generated by Django 5.1.5 on 2025-03-09 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0009_alter_product_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStatementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_stock', models.IntegerField(default=0)),
                ('received_stock', models.IntegerField(default=0)),
                ('issued_stock', models.IntegerField(default=0)),
                ('closing_stock', models.IntegerField(default=0)),
                ('variance', models.IntegerField(default=0)),
                ('remarks', models.CharField(choices=[('Normal', 'Normal'), ('Shortage', 'Shortage'), ('Surplus', 'Surplus')], default='Normal', max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='inventorystatement',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='inventorystatement',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_statements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorystatement',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorystatement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorystatement',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_statements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorystatement',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorystatement',
            name='store_location',
            field=models.CharField(default='Main Store', max_length=255),
        ),
        migrations.AddIndex(
            model_name='inventorystatement',
            index=models.Index(fields=['start_date', 'end_date'], name='stock_inven_start_d_2e6895_idx'),
        ),
        migrations.AddField(
            model_name='inventorystatementitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
        ),
        migrations.AddField(
            model_name='inventorystatementitem',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.inventorystatement'),
        ),
        migrations.AlterUniqueTogether(
            name='inventorystatementitem',
            unique_together={('statement', 'product')},
        ),
    ]
