# Generated by Django 5.1.5 on 2025-03-09 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_inventorystatementitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventorystatementitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventorystatement',
            name='items',
            field=models.ManyToManyField(related_name='inventory_statements', through='stock.InventoryStatementItem', to='stock.product'),
        ),
        migrations.AlterField(
            model_name='inventorystatementitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_entries', to='stock.product'),
        ),
        migrations.AlterField(
            model_name='inventorystatementitem',
            name='remarks',
            field=models.CharField(default='Normal', max_length=50),
        ),
        migrations.AlterField(
            model_name='inventorystatementitem',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='stock.inventorystatement'),
        ),
        migrations.AddIndex(
            model_name='inventorystatement',
            index=models.Index(fields=['store_location'], name='stock_inven_store_l_244411_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorystatementitem',
            index=models.Index(fields=['statement', 'product'], name='stock_inven_stateme_f31833_idx'),
        ),
    ]
