# Generated by Django 5.1.5 on 2025-03-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_alter_inventorystatementitem_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorystatementitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='inventorystatementitem',
            name='statement',
        ),
        migrations.RemoveField(
            model_name='inventorystatement',
            name='items',
        ),
        migrations.AlterModelOptions(
            name='inventorystatement',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='inventorystatement',
            name='stock_inven_id_a60c7b_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorystatement',
            name='stock_inven_date_a7249b_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorystatement',
            name='stock_inven_start_d_2e6895_idx',
        ),
        migrations.RemoveIndex(
            model_name='inventorystatement',
            name='stock_inven_store_l_244411_idx',
        ),
        migrations.RenameField(
            model_name='inventorystatement',
            old_name='date',
            new_name='generated_at',
        ),
        migrations.RemoveField(
            model_name='inventorystatement',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='inventorystatement',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='inventorystatement',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='inventorystatement',
            name='prepared_by',
        ),
        migrations.RemoveField(
            model_name='inventorystatement',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='inventorystatement',
            name='store_location',
        ),
        migrations.RemoveField(
            model_name='inventorystatement',
            name='total_income',
        ),
        migrations.RemoveField(
            model_name='inventorystatement',
            name='total_products_in_stock',
        ),
        migrations.RemoveField(
            model_name='inventorystatement',
            name='total_products_sold',
        ),
        migrations.AddField(
            model_name='inventorystatement',
            name='report_data',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='InventoryStatementItem',
        ),
    ]
