# Generated by Django 5.1.5 on 2025-03-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0012_remove_inventorystatementitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorystatement',
            name='report_data',
        ),
        migrations.AddField(
            model_name='inventorystatement',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventorystatement',
            name='total_products_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorystatement',
            name='total_products_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
