# Generated by Django 5.1.5 on 2025-03-10 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0013_remove_inventorystatement_report_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStatementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_stock', models.PositiveIntegerField(default=0)),
                ('received_stock', models.PositiveIntegerField(default=0)),
                ('invoiced_stock', models.PositiveIntegerField(default=0)),
                ('closing_stock', models.PositiveIntegerField(default=0)),
                ('variance', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Inventory Statement Item',
                'verbose_name_plural': 'Inventory Statement Items',
                'ordering': ['product__name'],
            },
        ),
        migrations.AlterModelOptions(
            name='inventorystatement',
            options={'ordering': ['-date'], 'verbose_name': 'Inventory Statement', 'verbose_name_plural': 'Inventory Statements'},
        ),
        migrations.RemoveField(
            model_name='inventorystatement',
            name='generated_at',
        ),
        migrations.RemoveField(
            model_name='inventorystatement',
            name='total_income',
        ),
        migrations.RemoveField(
            model_name='inventorystatement',
            name='total_products_in_stock',
        ),
        migrations.RemoveField(
            model_name='inventorystatement',
            name='total_products_sold',
        ),
        migrations.AddField(
            model_name='inventorystatement',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventorystatement',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inventorystatement',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorystatement',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='inventorystatement',
            constraint=models.UniqueConstraint(fields=('date',), name='unique_daily_statement'),
        ),
        migrations.AddField(
            model_name='inventorystatementitem',
            name='inventory_statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stock.inventorystatement'),
        ),
        migrations.AddField(
            model_name='inventorystatementitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.product'),
        ),
    ]
