# Generated by Django 5.1.5 on 2025-03-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0015_productstockupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorystatement',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventorystatement',
            name='total_products_in_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorystatement',
            name='total_products_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventorystatement',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
