# Generated by Django 5.1.5 on 2025-03-22 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0019_sale_seller_name_alter_sale_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dozen_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price when purchasing a dozen of this product.', max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_per_carton',
            field=models.PositiveIntegerField(default=0, help_text='Number of items contained in one carton (constant).'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='sale_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('bulk', 'Bulk'), ('dozen', 'Dozen')], default='regular', max_length=10),
        ),
    ]
