# Generated by Django 5.1.5 on 2025-03-22 22:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0020_product_dozen_price_product_quantity_per_carton_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dozen_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price when purchasing a dozen of this product.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
