# Generated by Django 5.1.5 on 2025-03-28 09:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0021_alter_product_dozen_price_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='custom_bulk_minimum',
            field=models.PositiveIntegerField(blank=True, help_text='Custom minimum bulk quantity for this sale item', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='dozen_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price when purchasing a dozen of this product.', max_digits=10, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
