# Generated by Django 5.1.5 on 2025-05-08 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('prepared_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_products_sold', models.PositiveIntegerField(default=0)),
                ('total_products_in_stock', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Inventory Statement',
                'verbose_name_plural': 'Inventory Statements',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('date',), name='unique_daily_statement')],
            },
        ),
        migrations.CreateModel(
            name='InventoryStatementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_stock', models.PositiveIntegerField(default=0)),
                ('received_stock', models.PositiveIntegerField(default=0)),
                ('invoiced_stock', models.PositiveIntegerField(default=0)),
                ('closing_stock', models.PositiveIntegerField(default=0)),
                ('variance', models.IntegerField(default=0)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('inventory_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='statement.inventorystatement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Inventory Statement Item',
                'verbose_name_plural': 'Inventory Statement Items',
                'ordering': ['product__name'],
            },
        ),
    ]
