# Generated by Django 5.1.5 on 2025-05-09 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_dozen_price_and_more'),
        ('statement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStockUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('quantity_change', models.IntegerField(help_text='Positive for received stock, negative for sold stock.')),
                ('notes', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_updates', to='products.product')),
            ],
        ),
    ]
