services:
  - type: web
    name: your-inventory-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn your_project_name.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-app-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".render.com,localhost,127.0.0.1"