# Generated by Django 5.1.5 on 2025-05-09 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='custom_bulk_minimum',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
